<p>To request data or related information, please submit this&nbsp;<a href="/contact-us/data">form</a>&nbsp;to Jon Hallas (312-386-8764)</p>

<ul class="items">
	<li class="clearfix"><strong><img alt="" src="/documents/10180/10751/Data-RegionalIndicators-thumb.png/d807de1f-b96c-459e-a4ad-7762714f9346?t=1385996814580" /><a href="/data/regional-indicators">Regional Indicators</a>.</strong>&nbsp;Each GO TO 2040 recommendation area includes a set of <a href="/data/regional-indicators">regional indicators</a> that serve as benchmarks for monitoring progress of plan implementation. This effort relates to CMAP&#39;s on-going <a href="/data/metropulse/">MetroPulse</a> partnership with The Chicago Community Trust.
	&nbsp;</li>
	<li class="clearfix"><strong><img alt="" src="/documents/10180/10751/Data-Demographics-thumb.png/005a27ff-8f35-405d-a398-b578110d8d4e?t=1385997123505" /><a href="/data/demographics">Demographics</a>.</strong>&nbsp;CMAP uses <a href="/data/demographics/census">Census</a> and other data products to prepare <a href="/data/demographics/population-forecast">forecasts</a>&nbsp;of population and employment for use in regional planning and policy analysis.</li>
	<li class="clearfix"><strong><img alt="" src="/documents/10180/10751/Data-LandUse-thumb.png/b6769559-7e42-4b0d-88c3-3a3cf93dcb55?t=1385997259589" /><a href="/data/land-use">Land Use Data</a>. &nbsp;</strong>Updated every five years, CMAP&#39;s&nbsp;<a href="/data/land-use/inventory">Land Use Inventory</a> supports regional planning and policy evaluations as well as local technical assistance activities. CMAP has also established a procedure for evaluating potential <a href="/data/land-use/developments-of-regional-importance">Developments of Regional Importance</a>. &nbsp;A partnership&nbsp;with Chicago Wilderness enhances information on &quot;<a href="/livability/open-space/green-infrastructure-vision">green infrastructure</a>&quot; -- the region&#39;s core conservation lands.</li>
	<li class="clearfix"><strong><img alt="" src="/documents/10180/10751/Data-Transportation-thumb.png/e544b0a8-e65c-4272-b6e4-f285f2f5f051?t=1385997301494" /><a href="/data/transportation">Transportation Data</a>.&nbsp;</strong>CMAP prepares <a href="/data/transportation/traffic">future traffic</a>&nbsp;projections, which are supported by a substantial regional <a href="/data/transportation/modeling">travel demand modeling</a> system and a large-scale <a href="/data/transportation/travel-tracker-survey">travel survey</a>. &nbsp;The agency also&nbsp;<span>monitors, analyzes, and provides information on </span><a href="/mobility/roads/cmp/performance-measurement">transportation system performance</a>.</li>
</ul>
